language: go
go:
  - "1.10"
  - "1.11"

before_install:
  - go get -t -v ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./test/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
